language: java

notifications:
   email:
   on_success: always




jobs:
  include:
    - stage: compile
    - script: gradle compileJava
    - stage: test
    if: branch = master
    - script: gradle test
